defmodule MCP.Router do
  @moduledoc ~S"""
  Phoenix router macros that mount the MCP endpoint and the OAuth
  authorization server in a couple of lines instead of hand-wiring every
  `forward`.

      import MCP.Router

      mcp_oauth "/", otp_app: :my_app, browser: :browser, api: :api
      mcp "/mcp", otp_app: :my_app, server: MyApp.MCP.Server

  ## No Phoenix dependency

  This library does not depend on `:phoenix`, and `mcp/2` and `mcp_oauth/2`
  do not change that. They `quote` code that calls `scope`, `pipe_through`,
  and `forward` unqualified, and never `require Phoenix.Router` or check
  `Code.ensure_loaded?/1`. Elixir resolves an unqualified call generated by a
  macro using the import table of the module the call is spliced into, not
  the module that wrote the `quote` block, so these names resolve inside
  *your* router, where `use MyAppWeb, :router` (or `use Phoenix.Router`
  directly) has already imported them, and never need to resolve inside this
  library at all. `mix compile` on `phx_mcp` alone, with no Phoenix anywhere
  in the dependency tree, is the proof: nothing in `mcp_oauth/2`'s body
  requires `scope`, `pipe_through`, or `forward` to exist, only that
  whatever module eventually calls the macro has already imported them.

  See `test/mcp/router_test.exs` for how this gets tested without Phoenix as
  a test dependency: a small stand-in module in `test/support` defines its
  own `scope/2`, `pipe_through/1`, and `forward/2,3` and records what it was
  called with, standing in for a real Phoenix router. Phoenix's own macros
  are considerably more elaborate (route helpers, pipeline validation,
  `Phoenix.Router.Route` structs), so this does not exercise Phoenix's
  routing table, only the one thing that is actually this library's to get
  right: that `mcp_oauth/2` and `mcp/2` expand into the calls they claim to,
  aimed at the caller's own `scope`/`pipe_through`/`forward`. Whether *those*
  correctly build a routing table is Phoenix's test suite's job, not this
  library's; the alternative (asserting on `Macro.expand/2` output) proves
  the same thing with less signal, since it stops at "produced this AST"
  rather than "this AST, run through something that behaves like a router,
  produced these routes."

  ## `mcp/2`

  Mounts the stateless MCP endpoint, `MCP.Plug`.

      mcp "/mcp", otp_app: :my_app, server: MyApp.MCP.Server

  Wrap it in your own `scope`/`pipe_through` if the endpoint needs one (rate
  limiting, for instance); `mcp/2` does not assume one exists, since whether
  it does is a fact about your app, not this library's to guess.

  Required:

    * `:otp_app`: the app `:auth` and friends default from, below
    * `:server`: a `use MCP.Server` module

  Everything else `MCP.Plug` accepts (`:auth`, `:allowed_origins`,
  `:allow_anonymous`, `:handle_ttl_ms`) may be passed explicitly, or left to
  default from `config :my_app, MCP.Plug, ...`. `:auth` is required by
  `MCP.Plug` itself with no library-level default, so a bare
  `mcp "/mcp", otp_app: :my_app, server: MyApp.MCP.Server` only compiles once
  `config :my_app, MCP.Plug, auth: {...}` supplies it. These values are
  module references and static option lists, not the kind of thing
  `runtime.exs` sensibly overrides per deploy, so unlike `mcp_oauth/2`'s
  issuer/scopes/default_resource, they are resolved once, while the macro
  expands, exactly like `:store` and `:consent` below.

  ## `mcp_oauth/2`

  Mounts the OAuth 2.1 authorization server: `/oauth/authorize` (RFC 6749
  §3.1), `/oauth/token` (§3.2), `/oauth/introspect` (RFC 7662),
  `/oauth/revoke` (RFC 7009), `/oauth/register` (RFC 7591), and
  `/.well-known/oauth-authorization-server` (RFC 8414), relative to `path`.

      mcp_oauth "/", otp_app: :my_app, browser: :browser, api: :api

  ### `:browser` and `:api` have no default

  Both are required whenever the endpoint they cover is mounted (see
  `:only`/`:except` below), and neither defaults to the conventional
  `:browser`/`:api` pipeline names a `phx.new` app happens to use. The split
  is security-relevant, not stylistic: `/oauth/authorize` is a session-bearing
  form POST. It needs the host's session and CSRF protection, and it needs
  whatever the host's browser pipeline assigns, because
  `c:MCP.OAuth.ResourceOwner.current_subject/1` reads the signed-in user off
  the conn that pipeline built. The other endpoints are credentialed,
  sessionless POSTs (and one GET, the metadata document) that must never see
  a session cookie. Defaulting `:browser`/`:api` to those atoms would
  silently do the right thing in a freshly generated app and silently do the
  wrong thing in one that renamed its pipelines, handing a cookie-bearing
  pipeline to endpoints that must never see one with no error and no
  warning. A required option with no default fails loudly instead, at
  compile time, in the one app that would otherwise get this wrong silently.

  ### `:only` and `:except`

  Subset the six endpoints (`:authorize`, `:token`, `:introspect`, `:revoke`,
  `:register`, `:metadata`) when the host does not want all of them. An app
  doing only `client_credentials` needs `:token` and `:metadata` and nothing
  else: no `:authorize`, no consent module, no browser pipeline, no
  `:register` (nothing dynamically registers a `client_credentials`-only
  client; the host provisions it directly through `MCP.OAuth.Store`).

      mcp_oauth "/", otp_app: :my_app, api: :api, only: [:token, :metadata]

  `:browser` is not required here, because excluding `:authorize` removes
  the one endpoint that needs it; requiring it anyway would defeat the point
  of being able to mount a client-credentials-only server with no browser
  pipeline at all. The same logic applies to `:api`: it is only required
  when at least one of `:token`, `:introspect`, `:revoke`, `:register`, or
  `:metadata` is included.

  Passing both `:only` and `:except`, or naming something outside the six
  endpoints, is a compile-time error.

  ### Identity: explicit option, then config, then error

  `:store`, `:resource_owner`, and `:consent` are module references, resolved
  in this order: the option passed to the macro call, then
  `config :otp_app, MCP.OAuth, store: ...` (see `MCP.OAuth.Config`), then (for
  `:store` and `:resource_owner`, when the endpoint set needs them) a
  compile-time error naming the option and the config key. `:consent` has no
  such requirement by itself, but mounting `:register` alongside `:authorize`
  with no `:consent` resolved either way is *also* a compile-time error:
  open registration is only safe behind a consent screen (see
  `MCP.OAuth.Plug.Authorize`'s moduledoc), and a host that forgets the
  consent module is a host that just made every signed-in resource owner
  one crafted link away from handing an attacker-registered client a code.

  `:issuer`, `:scopes`, and `:default_resource` resolve the same way as a
  first step, but the config fallback is not resolved while the macro
  expands: an explicit option is used as written (a literal, or an `{m, f,
  a}` the host wrote by hand, exactly as `MCP.OAuth.Plug.Metadata` and
  friends already accept), while an *unset* option becomes
  `{MCP.OAuth.Config, :fetch, [otp_app, key]}`, which reads
  `Application.get_env/2` fresh on every request. See `MCP.OAuth.Config`'s
  moduledoc for why: these three are the values most likely to need a
  `runtime.exs` override, and reading them while the router compiles would
  bake whatever `config.exs` said into the release, silently ignoring
  `runtime.exs` forever after.

  Other per-endpoint options pass straight through when given and are
  otherwise left to the underlying plug's own default: `:sign_in_path`
  (required, only when `:authorize` is mounted; see
  `MCP.OAuth.Plug.Authorize`), `:consent_max_age`, `:rate_limit` (see
  `MCP.OAuth.Plug.Register`; this library has no generic config home for a
  rate limiter, since what "too many" means is an app decision), and
  `:base_path`/`:cimd_supported` (see `MCP.OAuth.Plug.Metadata`).
  `:registration_endpoint` defaults to `true` when `:register` is included
  and is otherwise left unset, so mounting registration advertises it without
  an extra option; pass `false` explicitly to mount `:register` without
  advertising it.

  ### Topology stays in the router

  `path`, `:browser`, `:api`, and `:only`/`:except` are never read from
  config. `mix phx.routes` has to describe what the router actually does,
  and a mount path or a pipeline choice that came from config would make
  that command lie: the routes table would depend on values `mix phx.routes`
  cannot see. An app mounting two MCP servers at different paths with
  different auth (a public one and an internal one, say) expresses that by
  calling `mcp_oauth/2` and `mcp/2` twice with different `path`s and
  different explicit options; that cannot be pushed into one shared config
  key regardless.

  One consequence worth calling out: the `:metadata` endpoint
  (`/.well-known/oauth-authorization-server`) is fixed by RFC 8414 to an
  absolute path, but `mcp_oauth/2` mounts it relative to `path` like every
  other endpoint here, inside `scope(path)`. At `path: "/"` (the only value
  used in every example in this moduledoc, and the one `mix phx.routes` will
  show as correct) that is the same absolute path the RFC requires, so
  nothing is wrong. At any other `path`, the document lands somewhere other
  than where RFC 8414 clients look for it, exactly as it would if you wrote
  that `forward` by hand inside that `scope`; `mix phx.routes` will show the
  wrong path plainly, which is the honest failure mode this module is
  choosing on purpose over a magic special case for one of six endpoints.
  `MCP.OAuth.Plug.Metadata` accepts `mount: :endpoint` for hosts that need a
  non-root `mcp_oauth/2` mount and a correct metadata document at the same
  time: mount `:metadata` directly, ahead of the router, and pass
  `except: [:metadata]` here.

  ## Before and after

  Moxie's router wired all six OAuth endpoints and the MCP endpoint by hand
  (`web/lib/moxie_web/router.ex`, prior to this module):

  ```elixir
  # OAuth 2.0 authorization server, mounted from the MCP library. The scopes are
  # un-aliased so MCP.OAuth.Plug.* resolves as written, not under MoxieWeb.
  # Moxie provides only the store, the resource owner, and the issuer/scope
  # config; the endpoints themselves live in the library.

  # The resource owner is the member behind the session cookie, so authorize is
  # the one OAuth endpoint on the browser pipeline. It handles both methods: GET
  # renders the consent screen, POST is the member's answer to it, and
  # :protect_from_forgery covers that POST.
  scope "/" do
    pipe_through :browser

    forward "/oauth/authorize", MCP.OAuth.Plug.Authorize,
      store: Moxie.OAuth.Store,
      resource_owner: Moxie.OAuth.ResourceOwner,
      consent: MoxieWeb.OAuth.Consent,
      sign_in_path: "/sign-in",
      default_resource: {Moxie.OAuth, :mcp_resource, []}
  end

  # The rest are form-encoded, carry client credentials, and never the session
  # cookie, so no CSRF and no session.
  scope "/" do
    pipe_through :api

    forward "/.well-known/oauth-authorization-server", MCP.OAuth.Plug.Metadata,
      issuer: {Moxie.OAuth, :issuer, []},
      scopes: {Moxie.OAuth, :scope_names, []},
      registration_endpoint: true

    forward "/oauth/register", MCP.OAuth.Plug.Register,
      store: Moxie.OAuth.Store,
      scopes: {Moxie.OAuth, :scope_names, []},
      rate_limit:
        {MoxieWeb.MCP.RateLimiter, :check,
         Application.compile_env!(:moxie, [MoxieWeb.MCP, :registration_rate_limit])}

    forward "/oauth/token", MCP.OAuth.Plug.Token,
      store: Moxie.OAuth.Store,
      default_resource: {Moxie.OAuth, :mcp_resource, []}

    forward "/oauth/introspect", MCP.OAuth.Plug.Token,
      action: :introspect,
      store: Moxie.OAuth.Store,
      issuer: {Moxie.OAuth, :issuer, []}

    forward "/oauth/revoke", MCP.OAuth.Plug.Token,
      action: :revoke,
      store: Moxie.OAuth.Store
  end

  scope "/" do
    pipe_through :mcp

    forward "/mcp", MCP.Plug,
      server: MoxieWeb.MCP.Server,
      auth: Application.compile_env!(:moxie, [MoxieWeb.MCP, :auth]),
      allow_anonymous: true
  end

  forward "/.well-known/oauth-protected-resource", MCP.Plug.WellKnown,
    otp_app: :moxie,
    base_url: {MoxieWeb.Endpoint, :url, []},
    resource: "/mcp"
  ```

  Becomes, in `router.ex`:

  ```elixir
  import MCP.Router

  mcp_oauth "/", otp_app: :moxie, browser: :browser, api: :api,
    sign_in_path: "/sign-in",
    rate_limit:
      {MoxieWeb.MCP.RateLimiter, :check,
       Application.compile_env!(:moxie, [MoxieWeb.MCP, :registration_rate_limit])}

  scope "/" do
    pipe_through :mcp
    mcp "/mcp", otp_app: :moxie, server: MoxieWeb.MCP.Server
  end
  ```

  with `store`, `resource_owner`, `consent`, `issuer`, `scopes`, and
  `default_resource` moved to `config.exs`:

  ```elixir
  config :moxie, MCP.OAuth,
    store: Moxie.OAuth.Store,
    resource_owner: Moxie.OAuth.ResourceOwner,
    consent: MoxieWeb.OAuth.Consent,
    issuer: issuer,
    scopes: {Moxie.OAuth, :scope_names, []},
    default_resource: {Moxie.OAuth, :mcp_resource, []}

  config :moxie, MCP.Plug,
    auth: {MoxieWeb.MCP.Auth, store: Moxie.OAuth.Store, base_url: {MoxieWeb.Endpoint, :url, []}},
    allow_anonymous: true
  ```

  and `endpoint.ex` mounting the well-known resource document ahead of the
  router (Part 4; see `MCP.Plug.WellKnown`), rather than a bare `forward` at
  the bottom of the router that happens to work only because the mount path
  is `"/"`:

  ```elixir
  plug MCP.Plug.WellKnown, otp_app: :moxie, resource: "/mcp", mount: :endpoint
  ```

  Two macro calls and two config blocks stand in for the 82 hand-written
  lines above. `rate_limit:` and `sign_in_path:` stay explicit, spelled out
  in the router, because they are genuinely app-specific decisions (what
  "too many" means; where signed-out users go) with no generic config home a
  library can invent on the host's behalf; everything else that was config
  disguised as router code (`Application.compile_env!/2` calls sitting
  inside `forward` options) is now actually config, read where `runtime.exs`
  can reach it.
  """

  @oauth_endpoints [:authorize, :token, :introspect, :revoke, :register, :metadata]
  @api_endpoints [:metadata, :register, :token, :introspect, :revoke]

  @doc """
  Mounts `MCP.Plug`. See the moduledoc for options.
  """
  defmacro mcp(path, opts) do
    otp_app = fetch_required!(opts, :otp_app, "mcp/2")
    server = fetch_required!(opts, :server, "mcp/2")

    unless is_atom(otp_app) do
      raise ArgumentError, "mcp/2 :otp_app must be an atom, got: #{inspect(otp_app)}"
    end

    app_config = Application.get_env(otp_app, MCP.Plug, [])

    plug_opts =
      [server: server]
      |> put_default(:auth, opts, app_config)
      |> put_default(:allowed_origins, opts, app_config)
      |> put_default(:allow_anonymous, opts, app_config)
      |> put_default(:handle_ttl_ms, opts, app_config)
      |> compact()

    quote do
      forward(unquote(path), MCP.Plug, unquote(plug_opts))
    end
  end

  @doc """
  Mounts the OAuth 2.1 authorization server. See the moduledoc for options.
  """
  defmacro mcp_oauth(path, opts) do
    otp_app = fetch_required!(opts, :otp_app, "mcp_oauth/2")

    unless is_atom(otp_app) do
      raise ArgumentError, "mcp_oauth/2 :otp_app must be an atom, got: #{inspect(otp_app)}"
    end

    endpoints = resolve_endpoints!(opts)
    identity_config = Application.get_env(otp_app, MCP.OAuth, [])

    needs_store? =
      Enum.any?(endpoints, &(&1 in [:authorize, :token, :introspect, :revoke, :register]))

    needs_resource_owner? = :authorize in endpoints

    validate_pipelines!(opts, endpoints)

    store = resolve_module(opts, identity_config, :store, needs_store?, otp_app)

    resource_owner =
      resolve_module(opts, identity_config, :resource_owner, needs_resource_owner?, otp_app)

    consent = resolve_module(opts, identity_config, :consent, false, otp_app)

    validate_consent!(endpoints, consent)

    authorize_block = authorize_block(path, opts, endpoints, store, resource_owner, consent)
    api_block = api_block(path, opts, endpoints, otp_app, store)

    quote do
      unquote(authorize_block)
      unquote(api_block)
    end
  end

  ## -- mcp_oauth/2: endpoint AST builders -----------------------------------

  defp authorize_block(path, opts, endpoints, store, resource_owner, consent) do
    if :authorize in endpoints do
      otp_app = Keyword.fetch!(opts, :otp_app)
      browser = Keyword.fetch!(opts, :browser)
      sign_in_path = fetch_required!(opts, :sign_in_path, "mcp_oauth/2 (mounting :authorize)")

      authorize_opts =
        [
          store: store,
          resource_owner: resource_owner,
          consent: consent,
          sign_in_path: sign_in_path,
          default_resource: config_backed_value(opts, otp_app, :default_resource),
          consent_max_age: Keyword.get(opts, :consent_max_age)
        ]
        |> compact()

      quote do
        scope unquote(path) do
          pipe_through(unquote(browser))
          forward("/oauth/authorize", MCP.OAuth.Plug.Authorize, unquote(authorize_opts))
        end
      end
    end
  end

  defp api_block(path, opts, endpoints, otp_app, store) do
    forwards =
      for name <- @api_endpoints, name in endpoints do
        build_forward(name, path, opts, endpoints, otp_app, store)
      end

    case forwards do
      [] ->
        nil

      _ ->
        api = Keyword.fetch!(opts, :api)

        quote do
          scope unquote(path) do
            pipe_through(unquote(api))
            unquote_splicing(forwards)
          end
        end
    end
  end

  defp build_forward(:metadata, _path, opts, endpoints, otp_app, _store) do
    metadata_opts =
      [
        issuer: config_backed_value(opts, otp_app, :issuer),
        scopes: config_backed_value(opts, otp_app, :scopes),
        base_path: Keyword.get(opts, :base_path),
        registration_endpoint:
          Keyword.get(opts, :registration_endpoint, :register in endpoints || nil),
        cimd_supported: Keyword.get(opts, :cimd_supported)
      ]
      |> compact()

    quote do
      forward(
        "/.well-known/oauth-authorization-server",
        MCP.OAuth.Plug.Metadata,
        unquote(metadata_opts)
      )
    end
  end

  defp build_forward(:register, _path, opts, _endpoints, otp_app, store) do
    register_opts =
      [
        store: store,
        scopes: config_backed_value(opts, otp_app, :scopes),
        rate_limit: Keyword.get(opts, :rate_limit)
      ]
      |> compact()

    quote do
      forward("/oauth/register", MCP.OAuth.Plug.Register, unquote(register_opts))
    end
  end

  defp build_forward(:token, _path, opts, _endpoints, otp_app, store) do
    token_opts =
      [store: store, default_resource: config_backed_value(opts, otp_app, :default_resource)]
      |> compact()

    quote do
      forward("/oauth/token", MCP.OAuth.Plug.Token, unquote(token_opts))
    end
  end

  defp build_forward(:introspect, _path, opts, _endpoints, otp_app, store) do
    introspect_opts =
      [action: :introspect, store: store, issuer: config_backed_value(opts, otp_app, :issuer)]
      |> compact()

    quote do
      forward("/oauth/introspect", MCP.OAuth.Plug.Token, unquote(introspect_opts))
    end
  end

  defp build_forward(:revoke, _path, _opts, _endpoints, _otp_app, store) do
    revoke_opts = [action: :revoke, store: store] |> compact()

    quote do
      forward("/oauth/revoke", MCP.OAuth.Plug.Token, unquote(revoke_opts))
    end
  end

  ## -- mcp_oauth/2: validation and identity resolution -----------------------

  defp resolve_endpoints!(opts) do
    only = Keyword.get(opts, :only)
    except = Keyword.get(opts, :except)

    cond do
      only != nil and except != nil ->
        raise ArgumentError, "mcp_oauth/2 accepts either :only or :except, not both"

      only != nil ->
        validate_endpoint_names!(only)
        Enum.filter(@oauth_endpoints, &(&1 in only))

      except != nil ->
        validate_endpoint_names!(except)
        @oauth_endpoints -- except

      true ->
        @oauth_endpoints
    end
  end

  defp validate_endpoint_names!(names) do
    unknown = names -- @oauth_endpoints

    unless unknown == [] do
      raise ArgumentError,
            "mcp_oauth/2 :only/:except named unknown endpoint(s) #{inspect(unknown)}; " <>
              "expected a subset of #{inspect(@oauth_endpoints)}"
    end
  end

  defp validate_pipelines!(opts, endpoints) do
    needs_browser? = :authorize in endpoints
    needs_api? = Enum.any?(endpoints, &(&1 in @api_endpoints))

    missing =
      for {key, needed?} <- [browser: needs_browser?, api: needs_api?],
          needed?,
          not Keyword.has_key?(opts, key),
          do: key

    unless missing == [] do
      raise ArgumentError, """
      mcp_oauth/2 requires #{missing |> Enum.map(&":#{&1}") |> Enum.join(" and ")}, with no default.

      The split is security-relevant, not stylistic. /oauth/authorize is a
      session-bearing form POST: it needs the host's session and CSRF
      protection, and MCP.OAuth.ResourceOwner.current_subject/1 reads the
      signed-in user off whatever the host's browser pipeline assigns. The
      other OAuth endpoints are credentialed, sessionless requests that must
      never see a session cookie. Defaulting to :browser/:api would silently
      do the right thing in a freshly generated app and silently do the
      wrong thing in one that renamed its pipelines, so pass both explicitly
      (only the ones the mounted endpoints actually need; see :only/:except
      in the moduledoc).
      """
    end
  end

  defp resolve_module(opts, config, key, needed?, otp_app) do
    cond do
      Keyword.has_key?(opts, key) ->
        Keyword.fetch!(opts, key)

      Keyword.has_key?(config, key) ->
        Keyword.fetch!(config, key)

      needed? ->
        raise ArgumentError,
              "mcp_oauth/2 requires :#{key}, either as an explicit option or via " <>
                "config :#{otp_app}, MCP.OAuth, #{key}: ..."

      true ->
        nil
    end
  end

  defp validate_consent!(endpoints, consent) do
    if :authorize in endpoints and :register in endpoints and is_nil(consent) do
      raise ArgumentError, """
      mcp_oauth/2 mounts both :authorize and :register but no :consent module \
      was resolved (as an explicit option, or via config :otp_app, MCP.OAuth, \
      consent: ...).

      Open registration is only safe behind a consent screen: without one, an
      attacker can self-register a client, walk a signed-in resource owner to
      the authorize URL, and receive a code for that owner's data. Set
      :consent, or mount :register somewhere else with its own consent story
      (see MCP.OAuth.Plug.Authorize's moduledoc).
      """
    end
  end

  ## -- shared helpers ---------------------------------------------------------

  defp fetch_required!(opts, key, macro_name) do
    case Keyword.fetch(opts, key) do
      {:ok, value} -> value
      :error -> raise ArgumentError, "#{macro_name} requires :#{key}"
    end
  end

  # The two branches are not symmetric, and the asymmetry is the whole point.
  #
  # A call-site value arrived through the macro's own arguments, so it is
  # already AST and gets spliced as-is. A config value came from
  # `Application.get_env/2` at expansion time, so it is a runtime term that has
  # to be escaped before it can live inside a `quote`.
  #
  # Without that escape only self-quoting terms survive: atoms, numbers,
  # binaries, lists of those, and 2-element tuples. Everything else raises
  # "invalid quoted expression" at the host's compile time. That covers the
  # shapes this option actually takes in practice, which is why the omission
  # was invisible until someone wrote one:
  #
  #     auth: {MCP.Auth.OAuth, store: MyApp.OAuth.Store}          # 2-tuple, worked
  #     auth: {MCP.Auth.Static, base_url: {Endpoint, :url, []}}   # 3-tuple, raised
  #     auth: {MCP.Auth.Static, tokens: %{"t" => [...]}}          # map, raised
  #
  # `MCP.Router.config_backed_value/3` has a note on the same trap from the
  # other direction: building AST by hand instead of escaping a term.
  defp put_default(acc, key, opts, app_config) do
    case Keyword.fetch(opts, key) do
      {:ok, value} ->
        Keyword.put(acc, key, value)

      :error ->
        case Keyword.fetch(app_config, key) do
          {:ok, value} -> Keyword.put(acc, key, Macro.escape(value))
          :error -> acc
        end
    end
  end

  # An explicit option is used as written (literal or {m, f, a}, the host's
  # choice). Unset, it becomes an {m, f, a} pointing at MCP.OAuth.Config,
  # resolved fresh on every request by the plug's own call/2, not baked into
  # the router at compile time. See MCP.OAuth.Config's moduledoc.
  #
  # Built with `quote`, not as a bare Elixir tuple: unquote/1 only accepts
  # values that are already valid AST, and a plain 2-element tuple is
  # self-quoting but a 3-element one is not (Elixir represents literal
  # tuples of arity != 2 as a `{:{}, meta, args}` node, not as themselves).
  # Handing unquote/1 the raw runtime 3-tuple `{m, f, a}` directly raises
  # "tried to unquote invalid AST" rather than embedding it.
  defp config_backed_value(opts, otp_app, key) do
    case Keyword.fetch(opts, key) do
      {:ok, value} ->
        value

      :error ->
        quote do
          {MCP.OAuth.Config, :fetch, [unquote(otp_app), unquote(key)]}
        end
    end
  end

  defp compact(opts), do: Enum.reject(opts, fn {_key, value} -> is_nil(value) end)
end
