if Code.ensure_loaded?(Ecto.Schema) do
  defmodule MCP.OAuth.Store.Ecto.Client do
    @moduledoc """
    Ecto schema behind `mcp_oauth_clients`, a persistence detail of
    `MCP.OAuth.Store.Ecto`.

    Column names drop the `?` that `MCP.OAuth.Client`'s struct fields carry
    (`confidential`, not `confidential?`; `pkce_required`, not
    `pkce_required?`; `dynamically_registered`, not `dynamically_registered?`;
    `cimd`, not `cimd?`) -- Postgres identifiers do not take `?` without
    quoting every reference to them, so the store's conversion functions are
    where the `?` comes back.

    `pkce_required` and `cimd`/`dynamically_registered` are persisted rather
    than derived: a naive port of Moxie's store computes `pkce_required?` as
    `not confidential?`, which cannot express a confidential client an
    operator still wants forced through PKCE. Persisting the column is the
    more general default for a library that does not get to assume every
    confidential client trusts its own redirect handling.
    """

    use Ecto.Schema
    import Ecto.Changeset

    @primary_key {:id, :string, autogenerate: false}

    schema "mcp_oauth_clients" do
      field :secret_hash, :string
      field :redirect_uris, {:array, :string}, default: []
      field :scopes, {:array, :string}, default: []
      field :grant_types, {:array, :string}, default: []
      field :confidential, :boolean, default: false
      field :pkce_required, :boolean, default: true
      field :name, :string
      field :client_uri, :string
      field :logo_uri, :string
      field :dynamically_registered, :boolean, default: false
      field :cimd, :boolean, default: false
      timestamps(type: :utc_datetime)
    end

    @type t :: %__MODULE__{}

    @fields [
      :id,
      :secret_hash,
      :redirect_uris,
      :scopes,
      :grant_types,
      :confidential,
      :pkce_required,
      :name,
      :client_uri,
      :logo_uri,
      :dynamically_registered,
      :cimd
    ]

    # `id` is app-generated (MCP.OAuth.Secret.new/0), not autogenerated here,
    # so a collision surfaces through unique_constraint/3 as {:error, changeset}
    # rather than an uncaught Ecto.ConstraintError.
    @spec changeset(t(), map()) :: Ecto.Changeset.t()
    def changeset(client, attrs) do
      client
      |> cast(attrs, @fields)
      |> validate_required([:id])
      |> unique_constraint(:id, name: :mcp_oauth_clients_pkey)
    end
  end
end
